# Generated by Django 5.2.7 on 2025-10-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='topic',
            field=models.CharField(default='General Topic', max_length=100, verbose_name='Main Topic'),
        ),
    ]
